[build]
command = "npm run build"
publish = "dist"  # ✅ relative path

# Optional: Set environment variables like NODE_VERSION, etc.
[build.environment]

# For React Router or other SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
