name: Deploy Airflow to EC2

on:
  push:
    branches: [main]
    paths:
      - 'terraform/airflow/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.AIRFLOW_EC2_IP }}
        username: ubuntu
        key: ${{ secrets.AIRFLOW_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Starting Airflow deployment..."
          
          cd /opt/airflow
          
          docker compose down
          
          cp -r dags dags_backup_$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
          
          if [ ! -d "/tmp/repo" ]; then
            git clone https://github.com/AmmarAlzureiqi/optimyze.git /tmp/repo
          else
            cd /tmp/repo && git pull origin main
          fi
          
          echo "Copying Airflow files..."
          cp /tmp/repo/terraform/airflow/docker-compose.yml /opt/airflow/
          cp /tmp/repo/terraform/airflow/.env /opt/airflow/
          cp /tmp/repo/terraform/airflow/requirements.txt /opt/airflow/
          cp /tmp/repo/terraform/airflow/Dockerfile /opt/airflow/
          cp -r /tmp/repo/terraform/airflow/dags/* /opt/airflow/dags/ 2>/dev/null || true
          
          sudo chown -R 50000:50000 /opt/airflow/{dags,logs,plugins}
          chmod -R 755 /opt/airflow/{dags,logs,plugins}
          
          echo "Starting Airflow services..."
          docker compose up --build -d
          
          echo "Waiting for services to start..."
          sleep 60
          
          echo "Health check..."
          docker compose ps
          
          if curl -s http://localhost:8080 > /dev/null; then
            echo "Airflow UI is responding"
          else
            echo "Airflow UI not responding"
            docker compose logs
          fi
          
          rm -rf /tmp/repo
          
          echo "Deployment completed!"
    
    - name: Notify on failure
      if: failure()
      run: echo "Deployment failed"

      